apiVersion: v1
kind: Namespace
metadata:
  name: emqx-operator-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: edge1
  labels:
    tier: edge
    dc: dc1

---
apiVersion: v1
kind: Namespace
metadata:
  name: edge2
  labels:
    tier: edge
    dc: dc2

---

apiVersion: v1
kind: Namespace
metadata:
  name: cloud
  labels:
    tier: cloud
