#!/bin/bash -x

script_dir=$(dirname "$0")
# shellcheck source=./.env
source "$script_dir/.env"

doctl compute droplet delete -f edge1-worker-1 edge1-worker-2 edge2-worker-1 edge2-worker-2 edge1-worker-1 cloud-worker-1 cloud-worker-2 cloud-control-plane
