#!/bin/bash

vpc_network_prefix="{{VPC_NETWORK_PREFIX}}"
public_interface_name=$(route -n | awk '$1 == "0.0.0.0" {print $8}')

echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

sudo apt-get update
sudo apt-get install iptables iptables-persistent

iptables -t nat -A POSTROUTING -s "$vpc_network_prefix" -o "$public_interface_name" -j MASQUERADE
iptables-save > /etc/iptables/rules.v4
