kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: worker
  labels:
    tier: cloud
- role: worker
  labels:
    tier: cloud
- role: worker
  labels:
    tier: edge
- role: worker
  labels:
    tier: edge
