kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  # HERE cloud worker 1
  - role: worker
    labels:
      tier: cloud
  # HERE cloud worker 2
  - role: worker
    labels:
      tier: cloud
  # HERE edge worker 1 (DC1)
  - role: worker
    labels:
      tier: edge
      dc: dc1
  # HERE edge worker 2 (DC1)
  - role: worker
    labels:
      tier: edge
      dc: dc1
  # HERE edge worker 3 (DC2)
  - role: worker
    labels:
      tier: edge
      dc: dc2
  # HERE edge worker 4 (DC2)
  - role: worker
    labels:
      tier: edge
      dc: dc2
