apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  namespace: edge2
  name: emqx
spec:
  image: "emqx:5.0"
  coreTemplate:
    spec:
      replicas: 1
      nodeSelector:
        tier: edge
        dc: dc2
  replicantTemplate:
    spec:
      replicas: 1
