#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: nanomq-config
#data:
#  nanomq.conf: |+
#    system.num_taskq_thread = 4
#    system.max_taskq_thread = 4
#    system.parallel = 8
#    mqtt.session.msq_len = 65535
#
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: edge2
  name: edge2-broker
  labels:
    app: nanomq
    dc: dc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanomq
  template:
    metadata:
      name: broker
      labels:
        app: nanomq
        dc: dc2
    spec:
      nodeSelector:
        tier: edge
        dc: dc2
      containers:
        - name: nanomq
          image: emqx/nanomq:0.19.1-slim
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 8083
              name: ws
            - containerPort: 8883
              name: tls
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  namespace: edge2
  name: edgebroker
spec:
  type: ClusterIP
  selector:
    app: nanomq
    dc: dc2
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8083
      targetPort: 8083
      name: ws
    - port: 8883
      targetPort: 8883
      name: tls
