apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: temperature-sensor-1
  labels:
    model: temperature-sensor
spec:
  deviceModelRef:
    name: temperature-sensor
  protocol:
    customizedProtocol:
      protocolName: TemperatureSimulator
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - edge51 #pls give your edge node name
  propertyVisitors:
    - propertyName: minTemperature
      customizedProtocol:
        protocolName: TemperatureSimulator
    - propertyName: maxTemperature
      customizedProtocol:
        protocolName: TemperatureSimulator
status:
  twins:
    - propertyName: random-int
      reported:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "100"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "100"
    - propertyName: random-float
      reported:
        metadata:
          timestamp: '1550049403598'
          type: float
        value: "30"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: float
        value: "30"


#https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/device-management-enhance.md#new-device-instance-crd-sample
#apiVersion: apiextensions.k8s.io/v1beta1
#kind: CustomResourceDefinition
#metadata:
#              type: object
#            propertyVisitors:
#              description: 'Required: List of property visitors which describe how
#                to access the device properties. PropertyVisitors must unique by propertyVisitor.propertyName.'
#              items:
#                properties:
#                  customizedProtocol:
#                    description: customized protocol
#                    properties:
#                      protocolName:
#                        description: The name of protocol
#                        type: string
#                      configData:
#                        description: customized Config Data
#                        type: object
#                    required:
#                      - protocolName
#                      - configData
#                    type: object
#                  propertyName:
#                    description: 'Required: The device property name to be accessed.
#                      This should refer to one of the device properties defined in
#                      the device model.'
#                    type: string
#                  reportCycle:
#                    description: 'Define how frequent mapper will report the value.'
#                    format: int64
#                    type: integer
#                  collectCycle:
#                    description: 'Define how frequent mapper will collect from device.'
#                    format: int64
#                    type: integer
#                  customizedValues:
#                    description: Customized values for visitor of provided protocols
#                    type: object
#                required:
#                  - propertyName
#                type: object
#              type: array



#            data:
#              properties:
#                dataTopic:
#                  description: 'Topic used by mapper, all data collected from dataProperties
#                    should be published to this topic,
#                    the default value is $ke/events/device/+/data/update'
#                  type: string
#                dataProperties:
#                  description: A list of data properties, which are not required to be processed by edgecore
#                  items:
#                    properties:
#                      propertyName:
#                        description: 'Required: The property name for which the desired/reported
#                          values are specified. This property should be present in the
#                          device model.'
#                        type: string
#                      metadata:
#                        description: Additional metadata like filter policy, should be k-v format
#                        type: object
#                    required:
#                      - propertyName
#                    type: object
#                  type: array
#              type: object
#          required:
#            - deviceModelRef
#            - nodeSelector
#          type: object
#        status:
#          properties:
#            twins:
#              description: A list of device twins containing desired/reported desired/reported
#                values of twin properties. A passive device won't have twin properties
#                and this list could be empty.
#              items:
#                properties:
#                  desired:
#                    description: 'Required: the desired property value.'
#                    properties:
#                      metadata:
#                        description: Additional metadata like timestamp when the value
#                          was reported etc.
#                        type: object
#                      value:
#                        description: 'Required: The value for this property.'
#                        type: string
#                    required:
#                      - value
#                    type: object
#                  propertyName:
#                    description: 'Required: The property name for which the desired/reported
#                      values are specified. This property should be present in the
#                      device model.'
#                    type: string
#                  reported:
#                    description: 'Required: the reported property value.'
#                    properties:
#                      metadata:
#                        description: Additional metadata like timestamp when the value
#                          was reported etc.
#                        type: object
#                      value:
#                        description: 'Required: The value for this property.'
#                        type: string
#                    required:
#                      - value
#                    type: object
#                required:
#                  - propertyName
#                type: object
#              type: array
#          type: object
#  version: v1alpha2
