apiVersion: v1
kind: ConfigMap
metadata:
  namespace: edge1
  name: mapper-configmap
data:
  STAGE_STATUS: "dev"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "3000"
  SERVER_ADDR: "0.0.0.0:3000"
  SERVER_READ_TIMEOUT: "5s"
  SERVER_WRITE_TIMEOUT: "10s"
  SERVER_IDLE_TIMEOUT: "120s"
  MQTT_SUB_TOPICS: "dc1/sensor/mapper/+/state:dc1/sensor/mapper/+/temperature/data"
  MQTT_STATE_TOPICS: "dc1/sensor/mapper/+/state"
  MQTT_DATA_TOPIC: "dc1/sensor/mapper/+/temperature/data"
  MQTT_BROKER_URL: "tcp://emqx-listeners.edge1:1883"
  MQTT_PUBLISH_INTERVAL: "2s"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: edge1
  name: tsensor
  labels:
    app: tmapper
    dc: dc1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tmapper
      dc: dc1
  template:
    metadata:
      namespace: edge1
      labels:
        app: tmapper
        dc: dc1
    spec:
      nodeSelector:
        tier: edge
        dc: dc1
      containers:
        - name: mapper
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "125m"
          image: medmouine/mapper:latest
          ports:
            - containerPort: 3000
          env:
            - name: "DEVICE_LOCATION"
              value: "dc1"
            - name: MQTT_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
#          volumeMounts:
#            - name: source-code
#              mountPath: /go/src/mapper
          envFrom:
            - configMapRef:
                name: mapper-configmap
#      volumes:
#        - name: source-code
#          hostPath:
#            path: /go/src/mapper
#            type: Directory

---

apiVersion: v1
kind: Service
metadata:
  namespace: edge1
  name: tsensor-service
spec:
  type: ClusterIP
  selector:
    app: tmapper
  ports:
    - port: 3000
      targetPort: 8080
