podLabels:
  tier: cloud

nameOverride: "datalake"
fullnameOverride: "cloud-datalake"

nodeSelector:
  tier: cloud

adminUser:
  organization: "cloudorg"
  bucket: "iot-datalake"
  user: "admin"
  retention_policy: "0s"
  password: "influx_pas"
  token: "influx_token"
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /var/lib/influxdb2
  subPath: ""

#service:
#  type: ClusterIP
#  port: 80
#  targetPort: 8086
#  annotations: { }
#  labels: { }
#  portName: http
