---
# Source: influxdb2/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloud-datalake
  labels:
    app.kubernetes.io/name: datalake
    app.kubernetes.io/instance: influxdb-cloud
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: influxdb2-2.1.1
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datalake
      app.kubernetes.io/instance: influxdb-cloud
---
# Source: influxdb2/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-datalake
  labels:
    app.kubernetes.io/name: datalake
    app.kubernetes.io/instance: influxdb-cloud
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: influxdb2-2.1.1
---
# Source: influxdb2/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: datalake
    app.kubernetes.io/instance: influxdb-cloud
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: influxdb2-2.1.1
  name: cloud-datalake-auth
data:
  admin-token: "aW5mbHV4X3Rva2Vu"
  admin-password: "aW5mbHV4X3Bhcw=="
---
# Source: influxdb2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cloud-datalake
  labels:
    app.kubernetes.io/name: datalake
    app.kubernetes.io/instance: influxdb-cloud
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: influxdb2-2.1.1
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8086
  selector:
    app.kubernetes.io/name: datalake
    app.kubernetes.io/instance: influxdb-cloud
---
# Source: influxdb2/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloud-datalake
  labels:
    app.kubernetes.io/name: datalake
    app.kubernetes.io/instance: influxdb-cloud
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: influxdb2-2.1.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datalake
      app.kubernetes.io/instance: influxdb-cloud
  serviceName: "cloud-datalake"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datalake
        app.kubernetes.io/instance: influxdb-cloud
        tier: cloud
    spec:
      volumes:
        - name: data
          emptyDir: {}
      serviceAccountName: cloud-datalake
      containers:
        - name: influxdb2
          image: "influxdb:2.3.0-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          env:
            # Automated setup will not run if an existing boltdb file is found at the configured path.
            # This behavior allows for the InfluxDB container to reboot post-setup without encountering "DB is already set up" errors.
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            # The username to set for the system's initial super-user (Required).
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: admin
            # The password to set for the system's inital super-user (Required).
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-datalake-auth
                  key: admin-password
            # The name to set for the system's initial organization (Required).
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: cloudorg
            # The name to set for the system's initial bucket (Required).
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: iot-datalake
            # The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.
            - name: DOCKER_INFLUXDB_INIT_RETENTION
              value: 0s
            # The authentication token to associate with the system's initial super-user. If not set, a token will be auto-generated by the system.
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloud-datalake-auth
                  key: admin-token
            # Path to the BoltDB database.
            - name: INFLUXD_BOLT_PATH
              value: /var/lib/influxdb2/influxd.bolt
            # Path to persistent storage engine files where InfluxDB stores all Time-Structure Merge Tree (TSM) data on disk.
            - name: INFLUXD_ENGINE_PATH
              value: /var/lib/influxdb2
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
          - name: data
            mountPath: /var/lib/influxdb2
            subPath:
          resources:
            {}
      nodeSelector:
        tier: cloud
